export const UPDATE_APP_STATE = 'APP/UPDATE_APP_STATE';
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const SAVE_USER_DETAILS = "APP/SAVE_USER_DETAILS";
export const SAVE_USER_TYPE_DETAILS = "APP/SAVE_USER_TYPE_DETAILS";
export const SAVE_FIRST_TIME_LOGIN = "APP/SAVE_FIRST_TIME_LOGIN";
export const RESET_STORE = "APP/RESET_STORE";